# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from constants import globalConstants as c

class TestValidlogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_validlogin(self):
    self.driver.get(c.BASE_URL)
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.ID,c.USERNAME_ID).click()
    self.driver.find_element(By.NAME, c.USERNAME_ID).send_keys("standard_user")
    self.driver.find_element(By.ID, c.PASSWORD_ID).click()
    self.driver.find_element(By.NAME, c.PASSWORD_ID).send_keys("secret_sauce")
    self.driver.find_element(By.XPATH, "//div[@id=\'login_button_container\']/div/form/input").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'inventory_container\']/div/div").click()
    self.driver.close()
  
